Update main page and readme file
touredri/MyPorfolio pull request #1
Opened 2023-01-12 13:27 UTC by touredri

[ ] Customize main page with:
- html content
- styling in css file
[ ] Readme file with more information about the project
[ ] Add linters inside github workflows

2023-01-12 14:41 UTC, franclobo requested changes
Hi @touredri, 

# ♻️ Required Changes ♻️

![so-close-jim-halpert](https://user-images.githubusercontent.com/58642949/212094426-b41dd457-c9db-4ab3-bbe9-176dd8dd08b7.gif)

Good job so far!
You are doing it well 👏🏽 there are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights

- No linter errors ✔️ 
- Correct Github flow ✔️ 
- Descriptive PR ✔️ 
- Professional README file ✔️ 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-12 14:41 UTC, franclobo commented on style.css
> +}
- [ ] Please 🙏🏽 correct the dimension and the color of the hamburger button in the header and the font-style of the logo to be similar to the Figma template, it isn't italicized in the Figma design 👇🏽 
- [ ] Kindly reduce the space between the header and the title to be similar to the Figma template 👇🏽 

| Figma template | Your design |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/212090577-09e4699d-d9c0-49a8-91bc-a4943622b99d.png) ![image](https://user-images.githubusercontent.com/58642949/212091267-3fb8ab49-7c10-43bb-9c00-b973bcf9db63.png) | ![image](https://user-images.githubusercontent.com/58642949/212090455-15c86981-b3a3-4148-bf6a-8368e21ef544.png) ![image](https://user-images.githubusercontent.com/58642949/212091126-34fd9212-c324-4195-826c-0b21cdb10d87.png) |

2023-01-12 14:41 UTC, franclobo commented on style.css
> +  font-family: 'Poppins', sans-serif;
- [ ] Please 🙏🏽 import the font `Poppins` to use it to be similar to the Figma template.

2023-01-12 14:41 UTC, franclobo commented on style.css
> +}
- [ ] Please correct the spaces between the elements in the body to be similar to the Figma template 👇🏽 

| Figma template | Your design |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/212093889-35848ea7-2143-4fcd-a8ba-839ad670d650.png) | ![image](https://user-images.githubusercontent.com/58642949/212093969-e13cc179-b251-43d0-8260-ccb8ff7cd1c6.png) |

2023-01-12 14:41 UTC, franclobo commented on index.html
> +        </svg>
- [ ] For the background image kindly use the backgroud-image in CSS file. If an image is not part of the content (aesthetic reasons) use CSS background-image. 👀 [Check this link](https://stackoverflow.com/questions/492809/when-to-use-img-vs-css-background-image) for more info.If an image is not part of the content (aesthetic reasons) use CSS background-image. [Check this link](https://stackoverflow.com/questions/492809/when-to-use-img-vs-css-background-image) for more info.

2023-01-12 17:24 UTC, touredri commented on style.css
> +}
understand sir

2023-01-12 17:25 UTC, touredri commented on style.css
> +}
fix know

2023-01-12 17:54 UTC, touredri commented on index.html
> +        <i class="fa-solid fa-bars"></i>
don't understand hamburger button

2023-01-12 17:54 UTC, touredri commented on index.html
> +    </div>
ok

2023-01-12 18:09 UTC, touredri commented on index.html
> +        </svg>
don't understand this part sir

2023-01-13 11:00 UTC, iambenkis requested changes
# Required Changes :recycle:
![almost-there](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQp9z2Rq_bAJ42eRNxObBr1nKDUbZjLw2QqkQ&usqp=CAU)

### Hey @touredri  :wave:

### Highlights :1st_place_medal:

:heavy_check_mark: Following Linters 
:heavy_check_mark: Following GitHub Flow
:heavy_check_mark: Basic Structure is good 


Good job on implementing most of the requirements but there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional suggestions


_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @iambenkis in your question so I can receive the notification.


_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-13 11:00 UTC, iambenkis commented on index.html
> +        </div>
- [ ] As requested by the previous reviewer, the space between these social media icon should be the same as in the Figma template :100: , Kindly make sure you fix that :+1: 
- [ ] You should also attach links to these social media so that a user can click on them, and  be redirected to your social media profile, isn't it professional ? :smile: 

For example :+1: 

```bash
<a href="yourfacebook.com"><i class="fa-brands fa-angellist">
```
### Your design
![Screenshot from 2023-01-13 12-44-51](https://user-images.githubusercontent.com/80458199/212301950-79bad384-cb1e-49c1-b7bc-e69afc428309.png)


### Figma template

![Screenshot from 2023-01-13 12-45-08 (1)](https://user-images.githubusercontent.com/80458199/212302054-14fbcc49-5d1f-49ad-b593-1e80bef1b9ac.png)

2023-01-13 11:00 UTC, iambenkis commented on style.css
> +}
- [ ] Kindly adjust the margin/padding  left of this headline class, so it sticks the Figma design :+1: 

![Screenshot from 2023-01-13 12-50-53](https://user-images.githubusercontent.com/80458199/212304351-708c5b70-9b74-4981-99f5-d1dda97cb247.png)

2023-01-13 11:00 UTC, iambenkis commented on index.html
> +        <a href="#"><h4>LET’S CONNECT</h4></a>
- [ ] Kindly stick to the Figma design by removing the underline on this `LET'S CONNECT` text :+1: 

![Screenshot from 2023-01-13 12-51-34](https://user-images.githubusercontent.com/80458199/212304603-e9554d8a-a7ea-40e8-93d9-175c42a66f80.png)

2023-01-13 11:15 UTC, touredri commented on style.css
> +}
ok

2023-01-13 11:21 UTC, touredri commented on index.html
> +        <a href="#"><h4>LET’S CONNECT</h4></a>
ok

2023-01-13 12:09 UTC, Tadesse-Alemayehu approved these changes
### Hi @touredri 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![ST3D](https://user-images.githubusercontent.com/69077061/209420293-8e3384ab-0ec0-4570-ace6-db3b03775d97.gif)


## Highlights
 - [ ] Good job making the changes requested by the previous code reviewer. ✅
 - [ ]  Correct GitHub Flow. ✅
 - [ ]  Good commit history. ✅
 - [ ]  All linters passed ✅
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-13 12:09 UTC, Tadesse-Alemayehu commented on style.css
> +}
- [Optional] Dear @touredri, I see you have used a fixed `375px` size for your body. this prevents your page from being responsive in the future. Please consider using responsive sizes, something like `100%` to make sure your page can scale on different mobile screens.

![Screenshot 2023-01-13 150425](https://user-images.githubusercontent.com/69077061/212317024-e021c408-9117-472c-ae2c-487cecc29874.png)

2023-01-13 13:33 UTC, touredri commented on style.css
> +}
ok

2023-01-13 13:36 UTC, merged