Completement of mobile part
touredri/MyPorfolio pull request #2
Opened 2023-01-14 22:28 UTC by touredri

- [ ] Add work section
  - use grid 
  -use flex 
- [ ] about me section

2023-01-16 12:24 UTC, ha-manel requested changes
# STATUS: REQUIRED CHANGES ♻️

## Hi @touredri 👋 
Great job so far, There are some changes that need to be implemented in order to proceed to the next project 👍  

<img src="https://media3.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights:  
* All tests passed ✔️
* Professional README file ✔️

## Required Changes:

Since the contact section is not part of this milestone's requirement I won't be making comments on it. Good job on getting over with it though 👏 

- [ ] Please consider using best practices when you write commit messages, they should be capitalized sentences in the imperative form, example: "Add linters" instead of "added linters" or "linters are added" ... etc 👍 

_Kindly check the comments below_

## Optional:
- [x] Please consider making the width of the page 100% then centering all the sections using `flexbox`, this way the website will look awesome on all mobile and small screen sized 👍 

------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-16 12:24 UTC, ha-manel commented on index.html
> +            </button>
- [ ] Kindly use `a` or `button`, one of them is enough 💯 
- [ ] Kindly update all the buttons `background-color` and text `color` to match the design in Figma. Also, please fix the hover effect by using the right text `color` (white) 👍 

## Your design:
![image](https://user-images.githubusercontent.com/50721479/212675908-dffb5b4b-e214-41af-bb0d-b59462fdc1e6.png)
![image](https://user-images.githubusercontent.com/50721479/212675930-c19a7e6e-3dbb-49a7-bc43-8bc487d42ddd.png)

## Figma design:
![image](https://user-images.githubusercontent.com/50721479/212676021-f43c3295-ab4d-4fe8-b6f1-c1fa595770d2.png)
![image](https://user-images.githubusercontent.com/50721479/212675967-67fb976b-2574-49ba-9b30-85411187a431.png)

2023-01-16 12:24 UTC, ha-manel commented on index.html
> +              <li class="lang lang3">javascript</li>
- [ ] Good job with using a list tag here 👏 Kindly add the right `background-color` to each technology badge as shown in Figma 👍 

## Your design:
![image](https://user-images.githubusercontent.com/50721479/212676490-f0ab561b-6271-44f0-be33-36a4696ee6dd.png)

## Figma design:
![image](https://user-images.githubusercontent.com/50721479/212676513-46a9a383-54c9-4acb-be84-ffcb9a979580.png)

2023-01-16 12:24 UTC, ha-manel commented on index.html
> +      <section class="headline about">
- [ ] Kindly add the right `background-color` to the `body` element, then please add a white background to the sections as shown in Figma. Please add a `border-radius` to the top right corner of the about me section as shown in Figma 👍 

## Your design:
![image](https://user-images.githubusercontent.com/50721479/212676898-c6ad8094-a942-49a4-a7c1-a60c75766f41.png)

## Figma design:
![image](https://user-images.githubusercontent.com/50721479/212676940-9c3b108d-ce97-4c79-980d-fa5f0e6442d0.png)

2023-01-16 12:24 UTC, ha-manel commented on index.html
> +        </button>
- [ ] Kindly use `a` or `button` for this button and please add the right size for it to match the template 👍 

## Your design:
![image](https://user-images.githubusercontent.com/50721479/212677203-64439e5b-d55d-4f3e-a500-84728e65a5ce.png)

## Figma design:
![image](https://user-images.githubusercontent.com/50721479/212677231-3a7db4d9-e3e5-40dd-b51a-54e7e4a33259.png)

2023-01-16 12:34 UTC, touredri commented on index.html
> +            <h1>Tonic</h1>
true

2023-01-16 12:40 UTC, touredri commented on index.html
> +        </button>
I try by best for the best without success

2023-01-17 12:26 UTC, bobb-Rob approved these changes
## STATUS: APPROVED ✔️ 🍾 🍾 🍾 🥳 🥳 🥳 

Hi @touredri , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-17 12:26 UTC, bobb-Rob commented on index.html
> +        <a href="#"><h4>LET’S CONNECT</h4></a>
- [ ] [OPTIONAL] This was flagged as optional because the previous reviewer did not mention it. I suggest you implement this as it is a core requirement for this project. _Kindly remove the `a` tag and leave the `h4` because this is not the actual link but a heading to the social media icons below it._

2023-01-17 13:23 UTC, touredri commented on index.html
> +        <a href="#"><h4>LET’S CONNECT</h4></a>
ahh ok thanks

2023-01-17 13:31 UTC, merged

2023-01-17 13:32 UTC, touredri commented
Mobile part complete